spring:
  application:
    name: stock-service

server:
  port: 8761


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    hostname: localhost




  server:
    enableSelfPreservation: false
